### ISSUE TITLE
no equality operator for Range[T] and MutRange[T]

### ISSUE THREAD

**Issue by jangko** [status-im/nim-ranges#6]
I wonder why there is no equality operator such as `==` or `!=` for typedranges.
Is that intentional or some other reason?
If I'm going to implement them, should I use for loop or some other mechanism?

**Comment by data-man** [comment]
> some other mechanism

```memcmp``` like [memfiles.nim#L290](https://github.com/nim-lang/Nim/blob/devel/lib/pure/memfiles.nim#L290)?

**Comment by yglukhov** [comment]
`system.equalMem` should be perfectly fine
