### ISSUE TITLE
[RFC] proposal for concat operation

### ISSUE THREAD

**Issue by jangko** [status-im/nim-ranges#8]
recently, I encountered situation where I need to concatenate two or more ranges, but there is no concat or similar operations in typedranges module.

and this is my ideas for concat operation(some details are omitted for clarity):
* proc add/concat(a: MutRange, b: Range): MutRange {.discardable.} -> enable dotcall chain
* proc `someOperator`(a, b: Range): Range
* proc add/concat(x: varargs[Range]): Range

please share your thoughts about this, should we use `add` or `concat` or something else.
better use varargs or binary operation(2 arity), and what would be the someOperator, `+` or `&` or something else.

**Comment by yglukhov** [comment]
If concatenation always allocates a new seq for the resulting Range, it can always take `Range` and return `MutRange`. You're not talking about inplace reallocation, right?

**Comment by jangko** [comment]
> You're not talking about inplace reallocation, right?

no, but it can be, if desired

**Comment by yglukhov** [comment]
> no, but it can be, if desired

Tbh I can't see how it can be done. You can't know if other `Range`s refer to the underlying `seq` of the `Range` being reallocated, can you?

**Comment by jangko** [comment]
you're right, I forget it can also pointer to something else including itself

**Comment by yglukhov** [comment]
Ok then. I would suggest a `proc concat(v: varargs[Range]): MutRange` and a binary `&` shortcut.

**Comment by zah** [comment]
If we'll be allocating a new `seq`, why should we lie about the result type? It could be a regular sequence. The rationale is that we allow turning a `seq` into a range cheaply, but not the other way around.

**Comment by jangko** [comment]
I think we are getting close to the conclusion,
Ranges act like a View to the seq, and we will stick to that concept.
concat operation returning regular seq will conform to that concept, and prevent Ranges abuse.
